export type Role = 'owner' | 'full' | 'viewer'
export type ScreenKey = 'first-run' | 'families' | 'setup' | 'feed' | 'viewer' | 'composer' | 'family' | 'child' | 'member' | 'invite' | 'invite-create' | 'invites' | 'channel' | 'install' | 'settings' | 'archive' | 'overlay' | 'components' | 'themes'
export type CatalogEntry = {
  id: string; group: string; screen: ScreenKey; state: string; title: string
  source: string; purpose: string; interaction: string; role: string
}
type Definition = { group: string; screen: ScreenKey; source: string; purpose: string; interaction: string; role?: string; states: string[] }
const definitions: Definition[] = [
  { group: '01 First Run', screen: 'first-run', source: 'App.tsx; features/app/BootPreloader.tsx; features/welcome/WelcomeSplash.tsx', purpose: 'Вход и первое знакомство', interaction: 'Продолжить, создать код, подтвердить, повторить', states: ['boot', 'welcome-intro', 'welcome-continue', 'max-context', 'browser-login', 'login-starting', 'login-pending', 'login-redeeming', 'login-approved', 'login-expired', 'login-error', 'max-approval', 'max-approval-busy', 'max-approved', 'max-approval-error', 'auth-error', 'welcome-error', 'open-telegram'] },
  { group: '02 Families', screen: 'families', source: 'features/family/FamilyHubPage.tsx; App.tsx/FamilyController', purpose: 'Выбор приватного альбома', interaction: 'Открыть семью, создать, загрузить ещё, повторить', states: ['empty', 'one', 'multiple', 'owner', 'invited', 'unread', 'unread-unavailable', 'unread-not-enabled', 'needs-child', 'loading', 'error', 'stale', 'loading-more', 'more-error', 'creating', 'create-error', 'own-unavailable'] },
  { group: '02 Families', screen: 'setup', source: 'features/family/FamilyOnboarding.tsx', purpose: 'Создать семью и заполнить профиль ребёнка', interaction: 'Изменить поля, выбрать demo-фото, crop, сохранить, отменить', role: 'owner', states: ['create', 'child-setup', 'incomplete', 'edit', 'avatar', 'crop', 'saving', 'success', 'error', 'validation', 'cancel'] },
  { group: '03 Feed', screen: 'feed', source: 'features/feed/FeedPage.tsx; features/feed/presentation/FeedPresentation.tsx', purpose: 'Общая семейная лента', interaction: 'Открыть, отметить новое, действия, reactions, Add', states: ['all', 'empty', 'loading', 'error', 'unread', 'unread-empty', 'unread-unavailable', 'new-memories', 'loading-more', 'more-error', 'access-lost'] },
  { group: '04 Memory Types', screen: 'feed', source: 'features/feed/FeedPage.tsx; features/feed/presentation/MemoryCardPresentation.tsx; MemoryReactions.tsx; NoteStoryPresentation.tsx', purpose: 'Фото, видео, текст и голос в одной анатомии записи', interaction: 'Viewer, carousel, play, читать, удержать reaction, actions', states: ['photo', 'portrait', 'landscape', 'multi-photo', 'mixed', 'max-video', 'private-video', 'telegram-video', 'note', 'long-note', 'voice', 'voice-playing', 'voice-error', 'no-reactions', 'reactions', 'own-reaction', 'reaction-error', 'processing', 'readiness-unknown', 'readiness-checking', 'readiness-error', 'unavailable', 'media-error'] },
  { group: '05 Viewers', screen: 'viewer', source: 'features/feed/FeedPage.tsx/MixedMediaViewer; Attachment; PhotoSwipe; NoteStoryPresentation.tsx', purpose: 'Открыть воспоминание целиком', interaction: 'Назад, далее, play/pause, закрыть с возвратом к ленте', states: ['photo', 'carousel', 'mixed', 'video', 'video-playing', 'video-loading', 'processing', 'unknown', 'checking', 'check-error', 'unavailable', 'error', 'telegram-handoff', 'note', 'fullscreen', 'return'] },
  { group: '06 Add / Compose', screen: 'composer', source: 'features/composer/PhotoComposer.tsx; NoteComposer.tsx; ComposerForm.tsx; MemoryEditor.tsx; features/max-video-upload/VideoComposer.tsx', purpose: 'Сохранить или изменить воспоминание', interaction: 'Demo selection, reorder/remove, caption/date, local progress, retry/cancel', role: 'owner/full', states: ['photo', 'photo-empty', 'multi-photo', 'mixed', 'note', 'note-saving', 'note-success', 'note-error', 'note-validation', 'note-cancel', 'video', 'video-reserve', 'video-upload', 'video-processing', 'video-publishing', 'video-error', 'video-success', 'video-cancel', 'video-empty', 'video-selected', 'edit', 'edit-conflict', 'reserve', 'upload', 'processing', 'publishing', 'success', 'error', 'reserve-error', 'upload-error', 'finalize-error', 'publish-uncertain', 'restart-required', 'validation', 'cancel'] },
  { group: '07 Family', screen: 'family', source: 'features/family/FamilyScreen.tsx; features/memoly-ui/FamilyPresentation.tsx', purpose: 'Близкие и настройки выбранной семьи', interaction: 'Child, participant, invite, settings, archive, channel', states: ['owner', 'full', 'viewer', 'incomplete', 'loading', 'error', 'usage-error', 'leave', 'leave-busy', 'leave-error'] },
  { group: '07 Family', screen: 'child', source: 'features/family/ChildProfile.tsx; FamilyOnboarding.tsx', purpose: 'Профиль ребёнка', interaction: 'Изменить профиль или фото (owner), назад', states: ['complete', 'incomplete', 'no-date', 'avatar-loading', 'avatar-error'] },
  { group: '07 Family', screen: 'member', source: 'features/memoly-ui/MemberProfile.tsx; member-profile-model.ts', purpose: 'Профиль владельца, участника и свой профиль', interaction: 'Alias, access, self name/avatar, remove confirmation', states: ['owner', 'full', 'viewer', 'self', 'edit', 'saving', 'saved', 'error', 'conflict', 'avatar-upload', 'avatar-error', 'avatar-remove', 'remove', 'remove-error'] },
  { group: '08 Invites', screen: 'invite', source: 'features/family/InvitationScreens.tsx; features/family/model.ts; App.tsx', purpose: 'Принятие приглашения', interaction: 'Явно присоединиться, открыть альбом или повторить', states: ['valid', 'preview', 'joining', 'success', 'expired', 'revoked', 'used', 'already-member', 'other-family', 'invalid', 'loading', 'error'] },
  { group: '08 Invites', screen: 'invite-create', source: 'features/family/InvitationScreens.tsx/InviteFlow; InviteReady', purpose: 'Пригласить близкого', interaction: 'Имя, роль, создать, demo-copy/share, назад', role: 'owner/full', states: ['relative', 'friend', 'viewer', 'full', 'creating', 'created', 'copied', 'copy-error', 'shared', 'error'] },
  { group: '08 Invites', screen: 'invites', source: 'features/memoly-ui/FamilyInvitesPage.tsx', purpose: 'Активные ссылки', interaction: 'Отозвать с подтверждением, пригласить', role: 'owner/full', states: ['active', 'empty', 'revoke', 'revoking', 'revoked', 'error'] },
  { group: '09 MAX Channel', screen: 'channel', source: 'features/memoly-ui/FamilyPresentation.tsx/FamilyMaxChannelCard; features/family/useFamilyMaxChannelStatus.ts', purpose: 'Связь семейного канала с ботом', interaction: 'Инструкция, повторная проверка; без provider logic', states: ['unconfigured', 'connected', 'disconnected', 'permission-problem', 'loading', 'error', 'management', 'no-management'] },
  { group: '10 States', screen: 'install', source: 'features/pwa-install/PwaInstallPrompt.tsx; platform/pwa-install.ts; App.tsx/isMaxIos', purpose: 'Установка и браузерный переход', interaction: 'Demo install, dismiss, браузерная инструкция', states: ['android-offer', 'available', 'unavailable', 'dismissed', 'installed', 'standalone', 'ios-browser', 'cancelled', 'error'] },
  { group: '10 States', screen: 'settings', source: 'features/memoly-ui/SettingsSheet.tsx; FamilySettingsPage.tsx', purpose: 'Настройки, приватность, оформление', interaction: 'Theme, family name/timezone, archive, help/about/install', states: ['menu', 'family', 'saving', 'saved', 'error', 'appearance', 'privacy', 'about', 'install-entry'] },
  { group: '10 States', screen: 'archive', source: 'features/memoly-ui/FamilyArchivePage.tsx', purpose: 'Использование приватного хранилища', interaction: 'Повторить, назад', states: ['ready', 'no-quota', 'loading', 'error'] },
  { group: '10 States', screen: 'overlay', source: 'features/memoly-ui/AddSheetPresentation.tsx; features/feed/FeedPage.tsx; MemoryDeleteSpotlight.tsx; MemoryReactions.tsx; MemberProfile.tsx', purpose: 'Общие модальные действия и feedback', interaction: 'Открыть/закрыть, select, confirm/cancel, Escape и возврат focus', states: ['add', 'voice-video', 'voice-handoff', 'memory-actions', 'reactions', 'delete', 'deleting', 'delete-error', 'member-actions', 'remove-member', 'revoke-invite', 'cancel-composer', 'invite-result', 'error-banner', 'toast'] },
  { group: '11 Components', screen: 'components', source: 'UI v2 canonical components (new presentation only)', purpose: 'Проверка единого component system', interaction: 'Buttons, fields, feedback, sheets, dialog, reactions', states: ['primitives', 'typography', 'buttons', 'forms', 'feedback', 'family-hero', 'memory-card', 'navigation', 'overlays'] },
  { group: '12 Themes', screen: 'themes', source: 'features/theme/ThemeProvider.tsx (theme directions only)', purpose: 'Одна геометрия, шесть палитр', interaction: 'Выбрать тему, открыть Feed/Family', states: ['mint', 'rose', 'sky', 'lavender', 'apricot', 'sand'] },
]
export const catalog: CatalogEntry[] = definitions.flatMap((definition) => definition.states.map((state) => ({
  id: definition.screen + ':' + state, group: definition.group, screen: definition.screen,
  state, title: state, source: 'webapp/src/' + definition.source, purpose: definition.purpose,
  interaction: definition.interaction, role: definition.role ?? 'owner/full/viewer',
})))
export const screenKeys = [...new Set(catalog.map((entry) => entry.screen))]
export const groups = [...new Set(catalog.map((entry) => entry.group))]
export const screenLabels: Record<ScreenKey, string> = {
  'first-run': 'Первый запуск', families: 'Мои семьи', setup: 'Настройка семьи', feed: 'Лента',
  viewer: 'Просмотр', composer: 'Добавление', family: 'Семья', child: 'Профиль ребёнка',
  member: 'Участник', invite: 'Приглашение', 'invite-create': 'Пригласить', invites: 'Активные приглашения',
  channel: 'Канал MAX', install: 'Установка', settings: 'Настройки', archive: 'Семейный архив',
  overlay: 'Overlays', components: 'Компоненты', themes: 'Темы',
}
export function getEntry(id: string | null) { return catalog.find((entry) => entry.id === id) ?? catalog[0] }
