import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'
import assert from 'node:assert/strict'

const root = resolve(import.meta.dirname, '..')
const read = (relativePath) => readFileSync(resolve(root, relativePath), 'utf8')

test('Selectel Compose owns only an internal static service', () => {
  const compose = read('deploy/selectel/compose.yml.template')

  assert.match(compose, /services:\s*[\s\S]*\n\s+static:\s*\n/)
  assert.doesNotMatch(compose, /\n\s+webapp:\s*\n/)
  assert.match(compose, /image:\s*memoly-webapp:\$\{MEMOLY_WEBAPP_IMAGE_TAG(?::-[^}]*)?\}/)
  assert.doesNotMatch(compose, /\n\s+static:[\s\S]*?\n\s+ports:/)
  assert.doesNotMatch(compose, /\n\s+container_name:/)
  assert.match(compose, /\n\s+postgres:\s*\n/)
  assert.match(compose, /\/opt\/memoly\/env\/postgres\.env/)
  assert.match(compose, /\/opt\/memoly\/env\/backend\.env/)
  assert.match(compose, /pg_isready/)
  assert.match(compose, /test:\s*\["CMD-SHELL",\s*"bun -e[\s\S]*health\/ready/)
  assert.match(compose, /interval:\s*15s/)
  assert.match(compose, /retries:\s*12/)
  assert.match(compose, /command:\s*\[\s*["']bun["']\s*,\s*["']src\/worker\.ts["']\s*\]/)
  assert.match(compose, /command:\s*\[\s*["']bun["']\s*,\s*["']src\/scheduler\.ts["']\s*\]/)
  assert.match(compose, /MEMOLY_MAX_BOT_TOKEN|MAX_BOT_TOKEN/)
  assert.match(compose, /MEMOLY_MAX_WEBHOOK_SECRET|MAX_WEBHOOK_SECRET/)
  assert.match(compose, /MEMOLY_MAX_INBOX_ENCRYPTION_KEY|MAX_INBOX_ENCRYPTION_KEY/)
  assert.doesNotMatch(compose, /\.env\.production/)
  assert.match(compose, /name:\s*\$\{MEMOLY_EDGE_NETWORK:-memoly_default\}/)
})

test('edge and static Caddy templates preserve routing ownership', () => {
  const edge = read('deploy/selectel/Caddyfile.edge.template')
  const statik = read('deploy/selectel/Caddyfile.static.template')

  assert.doesNotMatch(edge, /auto_https\s+off/)
  assert.match(edge, /\/api\/spikes\/max-video\//)
  assert.match(edge, /reverse_proxy\s+max-video-spike-backend:3000/)
  assert.match(edge, /\/__spikes\/max-direct-video-upload/)
  assert.match(edge, /@max_direct_video_upload_spike\s+path\s+\/__spikes\/max-direct-video-upload\s+\/__spikes\/max-direct-video-upload\/*/)
  assert.match(edge, /reverse_proxy\s+max-video-spike-frontend:80/)
  assert.match(edge, /\/api\//)
  assert.match(edge, /\/storage\//)
  assert.match(edge, /\/webhooks\/telegram/)
  assert.match(edge, /\/webhooks\/max/)
  assert.match(edge, /reverse_proxy\s+backend:3000/)
  assert.match(edge, /handle\s*\{[\s\S]*reverse_proxy\s+static:80[\s\S]*\}/)
  assert.doesNotMatch(edge, /\/max-video-upload\//)
  assert.match(statik, /root\s+\*\s+\/srv/)
  assert.match(statik, /try_files\s+\{path\}\s+\/index\.html/)
})

test('redeploy script fails closed and exposes safe promotion phases', () => {
  const script = read('deploy/selectel/redeploy.sh')

  assert.match(script, /docker inspect[\s\S]*com\.docker\.compose\.project/)
  assert.match(script, /gateway.*compose|compose.*gateway/i)
  assert.match(script, /COMPOSE_PROJECT=\$\{COMPOSE_PROJECT:-memoly\}/)
  assert.match(script, /MEMOLY_EDGE_NETWORK:-memoly_default/)
  assert.match(script, /SERVER_ROOT=\$\{SERVER_ROOT:-\/opt\/memoly\}/)
  assert.match(script, /COMPOSE_FILE=\$\{COMPOSE_FILE:-"\$SERVER_ROOT\/compose\.yml"\}/)
  assert.match(script, /backups\/compose\.pre-selectel/)
  assert.match(script, /date.*%Y%m%d|date.*%s/)
  assert.match(script, /max_bot_token/)
  assert.match(script, /max_webhook_secret/)
  assert.match(script, /max_inbox_encryption_key/)
  assert.match(script, /GATEWAY_CADDY_CONFIG=\$\{GATEWAY_CADDY_CONFIG:-\/tmp\//)
  assert.match(script, /SERVER_ROOT.*\.selectel-deploy\.lock/)
  assert.match(script, /require_command flock/)
  assert.match(script, /flock -n 9/)
  assert.match(script, /docker cp[\s\S]*GATEWAY_CADDY_CONFIG/)
  assert.match(script, /Caddyfile[\s\S]*reload/)
  assert.match(script, /install[\s\S]*compose\.yml/)
  assert.doesNotMatch(script, /\.env\.production/)
  assert.match(script, /docker compose[\s\S]*config/)
  assert.match(script, /prisma\s+Migrate\s+status|migration status|migrate status/i)
  assert.match(script, /worker/)
  assert.match(script, /scheduler/)
  assert.match(script, /static/)
  assert.match(script, /health\/live/)
  assert.match(script, /health\/ready/)
  assert.match(script, /MEMOLY_PRODUCT_SHA/)
  assert.match(script, /MEMOLY_PRODUCT_SHA=\$\{MEMOLY_PRODUCT_SHA:-\}/)
  assert.match(script, /\$\{#tag\}.*40/)
  assert.match(script, /\*\[!a-f0-9\]\*/)
  assert.match(script, /backend image tag must equal MEMOLY_PRODUCT_SHA/)
  assert.match(script, /webapp image tag must equal MEMOLY_PRODUCT_SHA/)
  assert.match(script, /docker image inspect\s+"memoly-backend:/)
  assert.match(script, /docker image inspect\s+"memoly-webapp:/)
  assert.doesNotMatch(script, /compose pull/)
  assert.match(script, /compose up -d --no-deps --force-recreate backend/)
  assert.match(script, /compose exec -T backend bun -e[\s\S]*127\.0\.0\.1:3000\$\{endpoint\}/)
  assert.match(script, /for endpoint in \/health\/live \/health\/ready/)
  assert.match(script, /http:\/\/static:80/)
  assert.match(script, /activate_gateway/)
  assert.match(script, /reload-gateway.*disabled.*use deploy/i)
  assert.doesNotMatch(script, /Usage: redeploy\.sh .*reload-gateway/)
  assert.match(script, /caddy\s+validate/)
  assert.match(script, /caddy\s+reload/)
  assert.match(script, /in-place-file\.sh" activate/)
  assert.match(script, /in-place-file\.sh" restore/)
  assert.match(script, /gateway-mounted Caddyfile checksum/)
  assert.match(script, /ROLLED_BACK_AFTER_CADDY_ACTIVATION_FAILURE/)
  assert.match(script, /CADDY_ROLLBACK_FAILED_AFTER_ACTIVATION_FAILURE/)
  assert.match(script, /if \[ "\$rollback_ok" -eq 1 \]/)
  assert.doesNotMatch(script, /mv\s+-f\s+"\$edge_tmp"\s+"\$SERVER_EDGE_CADDYFILE"/)
  assert.match(script, /rollback/i)
  assert.match(script, /compose ps --status running --services/)
  assert.match(script, /required Compose service is not running/)
  assert.match(script, /validate_inputs rollback/)
  assert.doesNotMatch(script, /docker\s+rm(?:\s|$)/m)
  assert.doesNotMatch(script, /docker\s+rename(?:\s|$)/m)
  assert.doesNotMatch(script, /--remove-orphans/)

  const deployBody = script.slice(script.indexOf('deploy() {'), script.indexOf('\n}\n\nusage()'))
  const rollbackBody = script.slice(script.indexOf('rollback() {'), script.indexOf('\n}\n\ndeploy()'))
  assert.ok(deployBody.indexOf('wait_backend_internal') < deployBody.indexOf('promote_jobs'))
  assert.ok(deployBody.indexOf('promote_static') < deployBody.indexOf('verify_static_internal'))
  assert.ok(deployBody.indexOf('verify_static_internal') < deployBody.indexOf('activate_gateway'))
  assert.ok(deployBody.indexOf('activate_gateway') < deployBody.indexOf('readiness'))
  const prepareBody = script.slice(script.indexOf('prepare_configuration() {'), script.indexOf('\n}\n\nmigration_status()'))
  assert.ok(prepareBody.indexOf('validate_candidate_caddy') < prepareBody.indexOf('backup_server_state'))
  const activateBody = script.slice(script.indexOf('activate_gateway() {'), script.indexOf('\n}\n\ngateway_public_health()'))
  assert.ok(activateBody.indexOf('validate_candidate_caddy') < activateBody.indexOf('backup_gateway_caddyfile'))
  assert.ok(activateBody.indexOf('backup_gateway_caddyfile') < activateBody.indexOf('in-place-file.sh" activate'))
  assert.ok(rollbackBody.indexOf('verify_static_internal') < rollbackBody.indexOf('render_edge_candidate'))
  assert.ok(rollbackBody.indexOf('render_edge_candidate') < rollbackBody.indexOf('validate_candidate_caddy'))
  assert.ok(rollbackBody.indexOf('validate_candidate_caddy') < rollbackBody.indexOf('activate_gateway'))
  assert.ok(rollbackBody.indexOf('activate_gateway') < rollbackBody.indexOf('readiness'))

  for (const match of script.matchAll(/^\s*compose up .*$/gm)) {
    assert.match(match[0], /--no-deps/)
    assert.match(match[0], /--force-recreate/)
  }
})

test('rollback template keeps additive migrations and uses configured images', () => {
  const rollback = read('deploy/selectel/rollback.env.example')

  assert.match(rollback, /PREVIOUS_BACKEND_IMAGE/)
  assert.match(rollback, /PREVIOUS_WEBAPP_IMAGE/)
  assert.match(rollback, /MEMOLY_DB_ROLLBACK_ALLOWED=false/)
  assert.match(rollback, /no database|forward-only|migrations remain/i)
})
