export const webpIconNames = [
  'calendar',
  'chevron',
  'clock',
  'close',
  'family',
  'fullscreen',
  'edit',
  'gear',
  'home',
  'info',
  'lock',
  'more',
  'palette',
  'help-circle',
  'archive-box',
  'circle-info',
  'pencil',
  'note',
  'photo',
  'pause',
  'play',
  'plus',
  'retry',
  'heart',
  'heart-filled',
  'voice',
  'star',
  'settings-sliders',
  'trash',
  'trash-can',
  'video',
  'warning',
  'user',
] as const

export type WebpIconName = (typeof webpIconNames)[number]
export type WebpIconState = 'active' | 'default' | 'white'
