import { expect, test } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'

for (const width of [320, 360, 390, 430]) for (const orientation of ['portrait', 'landscape']) {
  test(`editor fits ${width}px ${orientation}, drags, zooms, saves and restores`, async ({ page, browserName }) => {
    await page.setViewportSize({ width, height: 740 })
    await page.goto(`/e2e/avatar-editor.html?orientation=${orientation}`)
    const dialog = page.getByRole('dialog', { name: 'Редактирование фотографии' })
    await expect(dialog).toBeVisible()
    await expect(page.getByRole('button', { name: 'Готово' })).toBeEnabled()
    await expect(page.locator('.reactEasyCrop_CropArea')).toHaveClass(/Round/)
    const surface = page.locator('.avatar-editor-surface')
    const surfaceBox = await surface.boundingBox()
    expect(surfaceBox?.width).toBeGreaterThanOrEqual(280)
    const cropArea = await page.locator('.reactEasyCrop_CropAreaRound').boundingBox()
    const editorBox = await dialog.boundingBox()
    expect(Math.abs(cropArea!.width - cropArea!.height)).toBeLessThanOrEqual(1)
    expect(cropArea!.x).toBeGreaterThanOrEqual(surfaceBox!.x - 1)
    expect(cropArea!.x + cropArea!.width).toBeLessThanOrEqual(surfaceBox!.x + surfaceBox!.width + 1)
    expect(cropArea!.x).toBeGreaterThanOrEqual(editorBox!.x - 1)
    expect(cropArea!.x + cropArea!.width).toBeLessThanOrEqual(editorBox!.x + editorBox!.width + 1)
    const cropImage = page.locator('.reactEasyCrop_Image')
    const beforeDrag = await cropImage.getAttribute('style')
    const imageBox = await cropImage.boundingBox()
    await page.mouse.move(imageBox!.x + imageBox!.width / 2, imageBox!.y + imageBox!.height / 2)
    await page.mouse.down()
    await page.mouse.move(imageBox!.x + imageBox!.width / 2 + 24, imageBox!.y + imageBox!.height / 2 + 18, { steps: 5 })
    await page.mouse.up()
    expect(beforeDrag).toContain('transform:')
    await page.getByRole('slider', { name: 'Масштаб' }).fill('1.7')
    await page.getByRole('button', { name: 'Готово' }).dblclick()
    await expect(dialog).toBeHidden()
    await expect(page.getByTestId('save-count')).toHaveText('1')
    const crop = JSON.parse(await page.getByTestId('saved-crop').textContent() || 'null') as AvatarCropLike
    expect(crop).toEqual(expect.objectContaining({ x: expect.any(Number), y: expect.any(Number), width: expect.any(Number), height: expect.any(Number) }))
    expect(crop.x).toBeGreaterThanOrEqual(0); expect(crop.y).toBeGreaterThanOrEqual(0)
    expect(crop.width).toBeGreaterThan(0); expect(crop.height).toBeGreaterThan(0)
    expect(crop.x + crop.width).toBeLessThanOrEqual(1.00001); expect(crop.y + crop.height).toBeLessThanOrEqual(1.00001)
    await page.getByRole('button', { name: 'Open editor' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByRole('button', { name: 'Готово' }).click()
    await expect(page.getByTestId('save-count')).toHaveText('2')
    const restored = JSON.parse(await page.getByTestId('saved-crop').textContent() || 'null') as AvatarCropLike
    expect(Math.abs(restored.x - crop.x)).toBeLessThan(0.002)
    expect(Math.abs(restored.y - crop.y)).toBeLessThan(0.002)
    expect(Math.abs(restored.width - crop.width)).toBeLessThan(0.002)
    expect(Math.abs(restored.height - crop.height)).toBeLessThan(0.002)
    await page.getByRole('button', { name: 'Open editor' }).click()
    await page.getByRole('button', { name: 'Сбросить' }).click()
    await mkdir(resolve('e2e/.artifacts/avatar-editor-qa'), { recursive: true })
    await page.screenshot({ path: resolve('e2e/.artifacts/avatar-editor-qa', `${browserName}-${width}-${orientation}.png`), fullPage: true })
    expect(await page.locator('body').evaluate((node) => node.scrollWidth)).toBeLessThanOrEqual(width)
    await page.getByRole('button', { name: 'Отмена' }).click()
    await expect(page.getByRole('dialog')).toBeHidden()
    expect(await page.getByTestId('save-count').textContent()).toBe('2')
  })
}

test('failed save leaves crop intact for Retry', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 740 })
  await page.goto('/e2e/avatar-editor.html?retry=1')
  const cropImage = page.locator('.reactEasyCrop_Image')
  const imageBox = await cropImage.boundingBox()
  await page.mouse.move(imageBox!.x + imageBox!.width / 2, imageBox!.y + imageBox!.height / 2)
  await page.mouse.down()
  await page.mouse.move(imageBox!.x + imageBox!.width / 2 + 35, imageBox!.y + imageBox!.height / 2 + 30, { steps: 4 })
  await page.mouse.up()
  expect(imageBox!.width).toBeGreaterThan(0)
  const cropBeforeRetry = await cropImage.getAttribute('style')
  await page.getByRole('button', { name: 'Готово' }).click()
  await expect(page.getByRole('alert')).toContainText('Synthetic save failure')
  expect(cropBeforeRetry).toContain('transform:')
  await page.getByRole('button', { name: 'Повторить' }).click()
  await expect(page.getByTestId('save-count')).toHaveText('1')
  const attempted = JSON.parse(await page.getByTestId('attempt-crop').textContent() || 'null') as AvatarCropLike
  const saved = JSON.parse(await page.getByTestId('saved-crop').textContent() || 'null') as AvatarCropLike
  expect(Math.abs(saved.x - attempted.x)).toBeLessThan(0.002)
  expect(Math.abs(saved.y - attempted.y)).toBeLessThan(0.002)
  expect(Math.abs(saved.width - attempted.width)).toBeLessThan(0.002)
  expect(Math.abs(saved.height - attempted.height)).toBeLessThan(0.002)
})

type AvatarCropLike = { x: number; y: number; width: number; height: number }
