import { expect, test } from '@playwright/test'

test('animation end reveals the button but only a double tap completes once', async ({ page }) => {
  await page.goto('/e2e/welcome-splash.fixture.html')
  const splash = page.locator('[data-slot="welcome-splash"]')
  const button = splash.locator('.continue-button')
  await expect(button).toBeDisabled()
  await page.locator('#fixture > button').first().evaluate((control: HTMLButtonElement) => control.click())
  await splash.locator('.footer').evaluate((footer) => footer.dispatchEvent(new AnimationEvent('animationend', { animationName: 'copyIn', bubbles: true })))
  await expect(button).toBeEnabled()
  await expect(page.getByLabel('Completion count')).toHaveText('0')
  await page.evaluate(() => {
    const control = document.querySelector<HTMLButtonElement>('[data-slot="welcome-splash"] .continue-button')!
    control.dispatchEvent(new MouseEvent('click', { bubbles: true }))
    control.dispatchEvent(new MouseEvent('click', { bubbles: true }))
  })
  await expect(page.getByLabel('Completion count')).toHaveText('1')
})

test('fallback timer reveals the control without leaving the splash; layout fits 320 by 568', async ({ page }) => {
  await page.addInitScript(() => {
    document.documentElement.style.setProperty('--host-inset-top', '24px')
    document.documentElement.style.setProperty('--host-inset-bottom', '18px')
  })
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/e2e/welcome-splash.fixture.html')
  const splash = page.locator('[data-slot="welcome-splash"]')
  const button = splash.locator('.continue-button')
  await splash.locator('.footer').evaluate((footer) => { (footer as HTMLElement).style.animationPlayState = 'paused' })
  await page.waitForTimeout(4_700)
  await expect(button).toBeEnabled()
  await expect(splash).toBeVisible()
  await expect(page.getByLabel('Completion count')).toHaveText('0')
  const bounds = await button.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(568)
  await page.screenshot({ path: 'e2e/.artifacts/welcome-splash-320x568.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 760 })
  const shorterPhoneBounds = await button.boundingBox()
  expect(shorterPhoneBounds).not.toBeNull()
  expect(shorterPhoneBounds!.x + shorterPhoneBounds!.width).toBeLessThanOrEqual(390)
  expect(shorterPhoneBounds!.y + shorterPhoneBounds!.height).toBeLessThanOrEqual(760)
  await button.click()
  await expect(page.getByLabel('Completion count')).toHaveText('1')
})

test('reduced motion and StrictMode effect replay never continue automatically', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/e2e/welcome-splash.fixture.html')
  const splash = page.locator('[data-slot="welcome-splash"]')
  const button = splash.locator('.continue-button')
  await page.locator('#fixture > button').first().evaluate((control: HTMLButtonElement) => control.click())
  await expect(button).toBeEnabled({ timeout: 2_500 })
  await expect(splash).toBeVisible()
  await expect(page.getByLabel('Completion count')).toHaveText('0')
  await page.locator('#fixture > button').nth(1).evaluate((control: HTMLButtonElement) => control.click())
  await expect(page.locator('[data-slot="welcome-splash"]')).toBeVisible()
  await expect(page.getByLabel('Completion count')).toHaveText('0')
})
